### ISSUE TITLE
obsolete tutorial notebook

### ISSUE THREAD

**Issue by templarares** [deepmind/acme#174]
Hi acme team!
I am a newbie to RL and Acme. I was trying to run the quickstart.ipynb and tutorial.ipynb in the examples\. The former ran smoothly. But when I tried to run the DP4GAgent example (i.e., the "dm-cartpole" environment), I failed to get it to work. Apparently some function calls in the tutorial notebook are obsolete. E.g., the tutorial still uses the argument " dataset: tf.data.Dataset" in the initialization of "d4pg.D4PGLearner()", which has been replaced by "dataset_iterator: Iterator[reverb.ReplaySample]" in commit 329aae50695ca0290d6c151b7bbd4cefb1ccf83d. It looks like one needs to use some ActorLearnerBuilder() class to build a DP4G agent now? But I have no idea how... I can't find any documents or examples online regarding this new method. Could you please help update the tutorials accordingly? Thank you so much!

**Comment by qstanczyk** [comment]
Can you give it a try now? We have pushed a new release of Acme (0.2.3). Please reopen if you still hit this problem.

**Comment by templarares** [comment]
Hi qstanczyk, 

Thanks for your response! I updated my Acme to the latest 0.2.4 version. But the tutorial note book still fails at the same place: 
dataset = datasets.make_dataset(
    server_address=replay_server_address,
    batch_size=256,
    environment_spec=environment_spec,
    transition_adder=True)
failed with: ValueError: The make_reverb_dataset factory function no longer requires specs as as they should be passed as a signature to the reverb.Table when it is created. Consider either updating your code or falling back to the deprecated dataset factory in acme/datasets/deprecated.
